const ERROR = {
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_INCORRECT_PASS: "AUTH_INCORRECT_PASS",
  AUTH_NOT_ACTIVATED: "AUTH_NOT_ACTIVATED",
  AUTH_BAD_LINK: "AUTH_BAD_LINK",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
};

module.exports = { ERROR };
